User avatar
IndyTechFellowship/United-Way-Web pull request #14
Opened 2016-11-30 00:47 UTC by bwencke

2016-11-30 00:48 UTC, bwencke commented
Probably want to actually get user data before merging this.

2016-11-30 01:33 UTC, garr741 requested changes

2016-11-30 01:33 UTC, garr741 commented on imports/ui/pages/users/UserPage.jsx
> +  avatarUrl: 'http://www.thewrap.com/wp-content/uploads/2015/11/Donald-Trump.jpg',
Uhh no.

2016-11-30 02:35 UTC, garr741 approved these changes

2016-11-30 02:41 UTC, ashleyzeg approved these changes

2016-11-30 02:41 UTC, ashleyzeg commented on imports/ui/pages/users/UserPage.jsx
>      display: "flex",
single quotes?

2016-12-12 01:05 UTC, bwencke commented
@garr741 @ashleyzeg @mhoc I changed this PR a lot since you guys approved it, so if you want to look at it again, that would be awesome. Also, "UserCard" will be moved once Ashley finished the about me and skills components.

2016-12-12 01:51 UTC, ashleyzeg approved these changes

2016-12-12 02:47 UTC, merged